In [1]:
%matplotlib qt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from scipy import stats
from sklearn.datasets import load_boston
from perceptron import Perceptron

In [2]:
breast_cancer = load_boston()
X = breast_cancer.data
Y = breast_cancer.target
Y = Y.reshape(-1, 1)

C:\Users\moham\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California

In [3]:
data_np = np.concatenate((Y, X), axis=1)
data = pd.DataFrame(data_np)
cor = data.corr()
cor.head(1)

0         1         2         3        4         5        6         7   \
0  1.0 -0.388305  0.360445 -0.483725  0.17526 -0.427321  0.69536 -0.376955   

         8         9         10        11        12        13  
0  0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663

In [4]:
data_selected = data[[0, 2, 6]]
data_selected.rename(columns={0: 'PRICE', 2: 'ZN', 6: 'RM'}, inplace=True)
data_selected.head(5)

C:\Users\moham\AppData\Local\Temp\ipykernel_13188\3963391592.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_selected.rename(columns={0: 'PRICE', 2: 'ZN', 6: 'RM'}, inplace=True)


PRICE    ZN     RM
0   24.0  18.0  6.575
1   21.6   0.0  6.421
2   34.7   0.0  7.185
3   33.4   0.0  6.998
4   36.2   0.0  7.147

In [5]:
Y = data_selected['PRICE'].to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(data_selected[['ZN', 'RM']].to_numpy(), Y, test_size=0.2, shuffle=True)

In [17]:
loss_trains = []
losss = []
η1s = []
η2s = []
for η1 in np.arange(0.0001, 0.001, 0.0002):
    for η2 in np.arange(.01, .1, .02):
        p = Perceptron(η1, η2, 150)
        loss_train = p.fit(X_train, Y_train)
        loss_trains.append({'η1': η1, 'η2': η1, 'loss_train': loss_train})
        losss.append(loss_train)
        η1s.append(η1)
        η2s.append(η2)
        print(f'η1: {"{:.4f}".format(η1)}, η2: {"{:.2f}".format(η2)}, loss_train: {"{:.5f}".format(loss_train)}')

η1: 0.0001, η2: 0.01, loss_train: 45.30087
η1: 0.0001, η2: 0.03, loss_train: 44.02533
η1: 0.0001, η2: 0.05, loss_train: 44.11617
η1: 0.0001, η2: 0.07, loss_train: 44.41645
η1: 0.0001, η2: 0.09, loss_train: 44.61916
η1: 0.0003, η2: 0.01, loss_train: 42.71344
η1: 0.0003, η2: 0.03, loss_train: 42.82902
η1: 0.0003, η2: 0.05, loss_train: 43.17183
η1: 0.0003, η2: 0.07, loss_train: 43.52143
η1: 0.0003, η2: 0.09, loss_train: 43.83879
η1: 0.0005, η2: 0.01, loss_train: 42.81222
η1: 0.0005, η2: 0.03, loss_train: 43.02921
η1: 0.0005, η2: 0.05, loss_train: 43.33667
η1: 0.0005, η2: 0.07, loss_train: 43.65013
η1: 0.0005, η2: 0.09, loss_train: 43.95578
η1: 0.0007, η2: 0.01, loss_train: 43.57593
η1: 0.0007, η2: 0.03, loss_train: 43.67463
η1: 0.0007, η2: 0.05, loss_train: 43.88655
η1: 0.0007, η2: 0.07, loss_train: 44.17933
η1: 0.0007, η2: 0.09, loss_train: 44.51317
η1: 0.0009, η2: 0.01, loss_train: 507228426895.37958
η1: 0.0009, η2: 0.03, loss_train: 7841971259591525138432.00000
η1: 0.0009, η2: 0.05, lo

In [21]:
# η1 = 0.0003
# η2 = 0.01

η1 = 0.00003
η2 = 0.001

In [18]:
i = np.argmin(losss)
η1 = η1s[i]
η2 = η2s[i]

In [26]:
p = Perceptron(η1, η2, 150)
loss_train = p.fit(X_train, Y_train)
Y_pred_train = p.predict(X_train)
print('loss_train:', loss_train)

loss_train: 55.5159411768442


In [24]:
p.W = p.W[0]
p.W = p.W[::-1] 

In [25]:
def parameter_surface(w, b):
    xy = np.zeros((7, 101,2))
    for i in range(7):
        for j in range(101):
            xy[i, j, :] = [i + 3, j]

    xx, yy = np.meshgrid(range(3,10), range(0,101))
    z = np.matmul(xy, w) + b
    z = z.reshape(z.shape[:2])
    return xx, yy, z

In [29]:
ax1 = plt.subplot(1, 2, 1, projection="3d")
ax2 = plt.subplot(1, 2, 2)
plt.pause(5)
for j in range(len(p.ws)):
    ax1.clear()
    ax1.set_title('Boston house prices')
    ax1.set_xlabel('RM')
    ax1.set_ylabel('ZN')
    ax1.set_zlabel('PRICE')
    ax1.legend(['data','perceptron prediction'])
    ax1.scatter(data_selected['RM'], data_selected['ZN'], data_selected['PRICE'], c='blue')
    W = p.ws[j]
    W = W[::-1] 
    xx, yy, z = parameter_surface(W, p.bs[j])
    ax1.plot_surface(xx, yy, z.T, alpha=0.4, color='g')

    ax2.clear()
    ax2.plot(p.losses_train[:j])
    ax2.set_title("Loss Train")
    ax2.set_xlabel("Epoch")
    ax2.set_ylabel("Loss")

    plt.pause(0.01)
plt.show()

KeyboardInterrupt: 

In [13]:
p.ws[j][0]

0.6260801449745504

In [12]:
p.ws

[array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756752]]),
 array([[0.25123373, 1.26756